name: ActionSetupforPython
on:
  workflow_dispatch:
jobs:
   echo-action-Python
runs-on: ubuntu-latest

steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup Python
      uses: actions/setup-python@v5.4.0
      with:
            node-version:'3.8'
    - name: Create directory
      run: mkdir artifacts && cp target/** artifacts
   
